name: Deploy Uptime Kuma

on:
    push:
        branches: [ "main" ]
        paths:
        - 'uptime-kuma/**'
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Deploy
              uses: ./.github/actions/deploy
              with:
                host: ${{ secrets.SOLITUDE_HOST }}
                service_root_dir: ${{ secrets.SOLITUDE_DEPLOY_DIR }}
                service_dir_name: uptime-kuma
                infisical_project_id: ${{ secrets.INFISICAL_PROJECT_ID }}
                infisical_client_id: ${{ secrets.INFISICAL_CLIENT_ID }}
                infisical_client_secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
                infisical_secret_path: /services/uptime-kuma